# Generated by Django 5.2 on 2025-05-09 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_product_allergy_info_alter_product_standard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='注文ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('shipping_full_name', models.CharField(max_length=100, verbose_name='配送先氏名')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='配送先郵便番号')),
                ('shipping_prefecture', models.CharField(max_length=50, verbose_name='配送先都道府県')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='配送先市区町村')),
                ('shipping_address1', models.CharField(max_length=255, verbose_name='配送先住所1(番地など)')),
                ('shipping_address2', models.CharField(blank=True, max_length=255, verbose_name='配送先住所2(建物名など)')),
                ('shipping_phone_number', models.CharField(max_length=20, verbose_name='配送先電話番号')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='合計金額(税抜)')),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'クレジットカード'), ('bank_transfer', '銀行振込')], max_length=50, null=True, verbose_name='支払い方法')),
                ('payment_status', models.CharField(choices=[('pending', '未払い'), ('paid', '支払い済み'), ('failed', '支払い失敗'), ('refunded', '返金済み')], default='pending', max_length=20, verbose_name='支払い状況')),
                ('order_status', models.CharField(choices=[('pending', '支払い待ち'), ('processing', '処理中'), ('shipped', '発送済み'), ('completed', '完了'), ('cancelled', 'キャンセル済み'), ('refunded', '返金済み')], default='pending', max_length=20, verbose_name='注文状況')),
                ('notes', models.TextField(blank=True, verbose_name='備考欄')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='注文者')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名(注文時)')),
                ('price_at_purchase', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='購入時単価')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='注文')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文商品',
                'verbose_name_plural': '注文商品',
            },
        ),
    ]
