# Generated by Django 5.2 on 2025-04-06 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('description', models.TextField(verbose_name='商品説明')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='カテゴリ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='価格 (円)')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(choices=[('kg', 'キログラム'), ('g', 'グラム'), ('ko', '個'), ('fukuro', '袋'), ('hako', '箱'), ('taba', '束')], max_length=20, verbose_name='単位')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品画像')),
                ('standard', models.CharField(blank=True, max_length=100, verbose_name='規格')),
                ('cultivation_method', models.CharField(blank=True, choices=[('conventional', '慣行栽培'), ('special', '特別栽培'), ('organic', '有機栽培 (JAS認証なし)'), ('organic_jas', '有機栽培 (JAS認証あり)'), ('natural', '自然栽培')], max_length=50, verbose_name='栽培方法')),
                ('harvest_時期', models.CharField(blank=True, max_length=100, verbose_name='収穫時期')),
                ('shipping_available_時期', models.CharField(blank=True, max_length=100, verbose_name='出荷可能時期')),
                ('allergy_info', models.CharField(blank=True, max_length=255, verbose_name='アレルギー情報')),
                ('storage_method', models.CharField(blank=True, max_length=255, verbose_name='保存方法')),
                ('is_visible', models.BooleanField(default=True, verbose_name='公開フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='生産者')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
    ]
