# Generated by Django 5.2 on 2025-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('pending', '審査中'), ('active', '販売中'), ('inactive', '販売停止')], db_index=True, default='draft', max_length=10, verbose_name='ステータス'),
        ),
    ]
