# Generated by Django 5.2 on 2025-04-25 14:30

from django.db import migrations  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_is_visible_product_status"),
    ]

    operations = []
