# Generated by Django 5.2 on 2025-04-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_load_initial_products'),
        ('products', '000X_load_initial_products'),
    ]

    operations = [
    ]
