# Generated by Django 5.2 on 2025-04-27 03:50

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_load_initial_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergy_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アレルギー情報'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='規格'),
        ),
    ]
