# Generated by Django 5.2 on 2025-04-07 13:09

import django.db.models.deletion # type: ignore
from django.conf import settings # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=255, verbose_name='農園名/事業者名')),
                ('location_prefecture', models.CharField(blank=True, max_length=50, verbose_name='所在地 (都道府県)')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='所在地 (市区町村)')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介/こだわり')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='プロフィール画像')),
                ('website_url', models.URLField(blank=True, verbose_name='ウェブサイトURL')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('certification_info', models.TextField(blank=True, verbose_name='認証情報')),
                ('is_producer', models.BooleanField(default=False, verbose_name='生産者フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'プロフィール',
                'verbose_name_plural': 'プロフィール',
            },
        ),
    ]
