# Generated by Django 5.2 on 2025-05-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.CharField(blank=True, max_length=255, verbose_name='番地など'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='建物名・部屋番号など'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='名 (カナ)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓 (カナ)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_user',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号 (ユーザー連絡用)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prefecture',
            field=models.CharField(blank=True, max_length=50, verbose_name='都道府県'),
        ),
    ]
